from .ngos import router as ngos_router
from .projects import router as projects_router
from .collaborations import router as collaborations_router
from .alerts import router as alerts_router
from .auth import router as auth_router
from .stations import router as stations_router
from .users import router as users_router
from .reports import router as reports_router
from .gov import router as gov_router
