from pydantic import BaseModel
from typing import Optional
from datetime import datetime

# 1. Base Schema
# Contains fields common to both creating and reading a station.
class StationBase(BaseModel):
    name: str
    location: Optional[str] = None
    latitude: float   # Pydantic ensures this is a number (e.g., 12.9716)
    longitude: float  # Pydantic ensures this is a number
    managed_by: Optional[str] = None

# 2. Create Schema
# Validates data when an admin creates a NEW station.
# Inherits everything from StationBase.
class StationCreate(StationBase):
    pass

# 3. Response Schema
# Defines what the API sends back to the Frontend.
# It includes 'id' and 'created_at' which are generated by the Database, not the user.
class StationResponse(StationBase):
    id: int
    created_at: datetime

    # This Config tells Pydantic to read data from the SQLAlchemy Model
    class Config:
        from_attributes = True